### PR TITLE
Fix filepath in run_program.ado

### PR DESCRIPTION
**Pull request by nicolajthor**
The global `welfare_git` should point to the global `welfare_git` as set in `metafile.do` and not to the subfolder `Welfare`. Thank you, @bgoldman930, for spotting this error. This fix does not affect any results but only improves usability of `run_program`.

### CODE REVIEW

**Comment by bgoldman930** [comment]
@nicolajthor it now runs properly without needing to adjust `run_program.ado`. One other issue I am running in to, though. When I open and do "run_program snap_intro" it runs through without issue. Then, if I want to run it again, it throws a "program lambask already defined" error so I end up needing to add a "cap prog drop labmask" to the top of my do file. Of course possible this is specific to my machine so might not be worth fixing, just flagging in case helpful.

**Review by bgoldman930 — APPROVED** [review]
This now works without issue. I flagged an issue with the "labmask" program but I am not sure if that is specific to my machine or with fixing.

**Comment by nicolajthor** [comment]
@bgoldman930 I was able to reproduce the error loading `labmask`. Could you check whether the now updated version works for you? It drops `labmask` before defining it in the `labmask` ado-file.

**Comment by nicolajthor** [comment]
Merging this after checking in with @bgoldman930

**Comment by bgoldman930** [comment]
@nicolajthor confirmed this now works for me as well -- sorry for being slow on this!

**Pull request merged**
